TestMVC/Models/CaseSearchParameterModel.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestMVC.Models;
using CommonObjectLibraryCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using TestMVC;

namespace TestMVC.Models
{

    public enum SearchTypes
    {
        [EnumDisplayName(DisplayName = "Case Reference")]
        CaseReference,
        [EnumDisplayName(DisplayName = "Client Reference")]
        ClientReference
    }

    public class CaseSearchParameters
    {
        public string SearchTerm { get; set; }
        public SearchTypes SearchType { get; set; }
        public bool ExactMatch { get; set; }
    }
}

TestMVC/Models/EditCaseModel.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestMVC.Models;
using CommonObjectLibraryCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace TestMVC.Models
{
    public class EditCase
    {
        public Case CaseToEdit { get; set; }
        public IEnumerable<SelectListItem> PotentialStatusList { get; set; }
        public IEnumerable<SelectListItem> CaseHandlerList { get; set; }
    }
}

TestMVC/Models/ErrorViewModel.cs
using System;
using CommonObjectLibraryCore;
using System.Collections.Generic;

namespace TestMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }


}

TestMVC/Controllers/CaseDetailController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestMVC.Models;
using CommonObjectLibraryCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace TestMVC.Controllers
{
    public class CaseDetailController : Controller
    {

        private readonly ProjectContext _context;


        public CaseDetailController(ProjectContext context)
        {
            _context = context;
        }

        public IActionResult Index(int id)
        {
            var caseToView = _context.Cases.FirstOrDefault(c => c.CaseId == id);

            return View(caseToView);
        }
        public IActionResult AddCase()
        {
            var newCase = new Case();
            ViewBag.ClientId = new SelectList(_context.Clients.AsNoTracking().ToList(), "ClientEntityId", "ClientName");
            newCase.CaseReference = "PENDING";
            return View(newCase);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddCase(Case newCase)
        {
            throw new NotImplementedException();
        }

        public IActionResult EditBasicCase(int id)
        {
            var editCase = _context.Cases
                    .Include(c => c.Client).AsNoTracking().FirstOrDefault(c => c.CaseId == id);

            ViewBag.CurrentStatusId = new SelectList(_context.CaseStatusList.AsNoTracking().ToList(), "CaseStatusId", "CaseStatusName");
            ViewBag.CaseHandlerId = new SelectList(_context.Users.AsNoTracking().ToList(), "UserEntityId", "FullName");
            return View(editCase);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBasicCase(int? id)
        {
            var targetCase = await _context.Cases.FirstOrDefaultAsync(c => c.CaseId == id);

            if (ModelState.IsValid)
            {


                if (await TryUpdateModelAsync<Case>(
                    targetCase,
                    "",
                    c => c.ClientReference, c => c.CurrentStatusId, c => c.CaseHandlerId
                ))
                {
                    try
                    {
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateException /* ex */)
                    {
                        //Log the error (uncomment ex variable name and write a log.)
                        ModelState.AddModelError("", "Unable to save changes. " +
                            "Try again, and if the problem persists, " +
                            "see your system administrator.");
                    }
                    return RedirectToAction(nameof(Index), new { id = id });
                }
            }

            ViewBag.CaseStatusId = new SelectList(_context.CaseStatusList.AsNoTracking().ToList(), "CaseStatusId", "CaseStatusName");
            ViewBag.CaseHandlerId = new SelectList(_context.Users.AsNoTracking().ToList(), "UserEntityId", "FullName");

            var myCase = _context.Cases
                    .Include(c => c.Client).AsNoTracking().FirstOrDefault(c => c.CaseId == id);

            return View(myCase);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestMVC/Controllers/CasesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestMVC.Models;
using CommonObjectLibraryCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.ViewFeatures;


namespace TestMVC.Controllers
{
    public class CasesController : Controller
    {
        private string loggedUser = "Ian Boggs";
        private readonly ProjectContext _context;


        public CasesController(ProjectContext context)
        {
            _context = context;
        }

        public IActionResult CaseSearch()
        {
            var searchParameters = new CaseSearchParameters();
            return View(searchParameters);
        }

        [HttpPost]
        public PartialViewResult CaseSearchResult(CaseSearchParameters searchParams)
        {
            var columnName = Enum.GetName(typeof(SearchTypes), searchParams.SearchType);
            var filter = CommonFunctions.CreateFilter<Case, string>(columnName, searchParams.SearchTerm.ToLower(), searchParams.ExactMatch);

            var caseList = _context.Cases.Include(c => c.Client).AsNoTracking().Where(filter).ToList();

            return PartialView("_CaseSearchResult", caseList);
        }


        public IActionResult Index()
        {
            var allCases = _context.Cases.ToList();

            return View(allCases);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestMVC.Models;
using CommonObjectLibraryCore;
using Microsoft.AspNetCore.Mvc.ViewFeatures;


namespace TestMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ProjectContext _context;


        public HomeController(ProjectContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            return View();
        }




        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestMVC/Views/CaseDetail/AddCase.cshtml
@using CommonObjectLibraryCore
@using TestMVC.Models
@model Case
@{
    ViewData["Title"] = $"Add New Case";
}
@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<div>
    <h1 class="display-6">Create New Case </h1>

    <form id="NewCaseForm">

        <div class="form-group row">
            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.Client.ClientName, new {htmlAttributes = new { @class ="col-sm-2 col-form-label" }})<br>
                @Html.DropDownListFor(model => model.Client.ClientName,
                new SelectList(ViewBag.ClientId,"Value","Text"),"-Select Client-", new { @class ="custom-select custom-select-sm" })
                <span asp-validation-for="@Model.ClientId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.ClientReference, new {htmlAttributes = new { @class ="col-sm-2 col-form-label" }})
                @Html.EditorFor(model => model.ClientReference,new {htmlAttributes = new { placeholder = "Client Reference",@class ="form-control form-control-sm" }})
                <span asp-validation-for="@Model.ClientReference" class="text-danger"></span>
            </div>
        </div>
    </form>


</div>

TestMVC/Views/CaseDetail/EditBasicCase.cshtml
@using CommonObjectLibraryCore
@using TestMVC.Models
@model Case
@{
    ViewData["Title"] = $"Edit Case {@Model.CaseReference}";
}
@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}
<div class="text-center">
    <h1 class="display-4">Edit Case @Model.CaseReference</h1>
    <p>Select the new case detail below</p>
    <form method="post">
        @Html.HiddenFor(model => model.CaseId)
        <table class="table table-striped table-hover">
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.CaseReference)
                </td>
                <td>
                    @Html.DisplayFor(model => model.CaseReference)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.CurrentStatus)
                </td>
                <td>
                    @Html.DropDownListFor(model => model.CurrentStatusId,
                    new SelectList(ViewBag.CurrentStatusId,"Value","Text"),"-Select Status-",new { @class =
                    "form-control" })
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.CaseHandler)
                </td>
                <td>
                    @Html.DropDownListFor(model => model.CaseHandlerId,
                    new SelectList(ViewBag.CaseHandlerId,"Value","Text"),"-Select Case Handler-",new { @class =
                    "form-control" })
                    <span asp-validation-for="@Model.CaseHandlerId" class="text-danger"></span>
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Client.ClientName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Client.ClientName)
                </td>
            </tr>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.ClientReference)
                </td>
                <td>
                    @Html.EditorFor(model => model.ClientReference)
                </td>
            </tr>
        </table>
        <p><button type="submit">Submit</button></p>
        <a asp-action="Index" asp-route-id="@Model.CaseId">Back to List</a>
    </form>

</div>

TestMVC/Views/CaseDetail/Index.cshtml
@using CommonObjectLibraryCore
@model Case
@{
    ViewData["Title"] = $"Case Summary - {@Model.CaseReference}";
}

<div class="text-center">
    <h1 class="display-4">Case Summary For @Model.CaseReference</h1>
    <p>Here is the case summary for this case</p>

    <table class="table table-striped table-hover">
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.CaseReference)
            </td>
            <td>
                @Html.DisplayFor(model => model.CaseReference)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.CurrentStatus)
            </td>
            <td>
                @Html.DisplayFor(model => model.CurrentStatus.CaseStatusName)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.CaseHandler)
            </td>
            <td>
                @Html.DisplayFor(model => model.CaseHandler.FullName)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Client.ClientName)
            </td>
            <td>
                @Html.DisplayFor(model => model.Client.ClientName)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.ClientReference)
            </td>
            <td>
                @Html.DisplayFor(model => model.ClientReference)
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <a asp-action="EditBasicCase" asp-route-id="@Model.CaseId">Edit Details</a>
            </td>

        </tr>
    </table>

</div>

TestMVC/Views/CaseSummary/Index.cshtml
@using CommonObjectLibraryCore
@model Case
@{
    ViewData["Title"] = $"Case Summary - {@Model.CaseReference}";
}

<div class="text-center">
    <h1 class="display-4">Case Summary For @Model.CaseReference</h1>
    <p>Here is the case summary for this case</p>

    <table class="table table-striped table-hover">
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.CaseReference)
            </td>
            <td>
                @Html.DisplayFor(model => model.CaseReference)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.CurrentStatus)
            </td>
            <td>
                @Html.DisplayFor(model => model.CurrentStatus.CaseStatusName)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.CaseHandler)
            </td>
            <td>
                @Html.DisplayFor(model => model.CaseHandler.FullName)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.Client.ClientName)
            </td>
            <td>
                @Html.DisplayFor(model => model.Client.ClientName)
            </td>
        </tr>
        <tr>
            <td>
                @Html.DisplayNameFor(model => model.ClientReference)
            </td>
            <td>
                @Html.DisplayFor(model => model.ClientReference)
            </td>
        </tr>
    </table>

</div>

TestMVC/Views/Cases/CaseSearch.cshtml
@model CaseSearchParameters
@{
    ViewData["Title"] = "Case Search";
}

@section Scripts {
@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<div>
    <h1 class="display-6">Case Finder</h1>


    <div class="form-group">
        <form id="SearchForm" class="form-inline">
            
            @Html.DropDownListFor(m => m.SearchType,
            Model.SearchType.ToSelectList()
            ,"Select Type Of Search",new { @id="searchFormSearchType", @class ="form-control mb-2 mr-sm-2 form-control-sm" })
            <div class="input-group mb-2 mr-sm-2">
                
                @Html.EditorFor(x => x.SearchTerm,new {htmlAttributes = new { @id="searchFormSearchTerm",@class ="form-control form-control-sm",placeholder = "Enter search term" }})
            </div>
            <div class="form-check mb-2 mr-sm-2">
                @Html.EditorFor(model => model.ExactMatch,new { @id="searchFormExactMatch", @class ="form-check-input form-control-sm" })
                <label class="form-check-label" for="searchFormExactMatch">&nbsp;Exact Match ?</label>
            </div>
            
            <input id="btnSearch" type="button" class="btn btn-primary" value="Search" />
        </form>
    </div>

    <div id="resultArea">
    </div>
</div>
<script>

    $('#btnSearch').on('click', function (e) {
        var formData = $('#SearchForm').serialize()
        GetSearchResult(formData);
    });

    function GetSearchResult(filters) {
        $.ajax({
            url: '/Cases/CaseSearchResult',
            type: 'POST',
            cache: false,
            async: true,
            dataType: "html",
            data: filters
        })
            .done(function (result) {
                $('#resultArea').html(result);
            }).fail(function (xhr) {
                console.log('error : ' + xhr.status + ' - '
                    + xhr.statusText + ' - ' + xhr.responseText);
            });
    }</script>

TestMVC/Views/Cases/Index.cshtml
@using CommonObjectLibraryCore
@model IEnumerable<Case>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Case List</h1>
    <p>There are a total of @Model.Count() cases in the system for which you are the case handler</p>

    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.CaseReference)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Client.ClientName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ClientReference)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var b in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="CaseDetail" asp-action="Index" asp-route-id="@b.CaseId">@b.CaseReference</a>

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => b.Client.ClientName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => b.ClientReference)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p><button class="btn btn-primary" id="load">Load</button></p>


</div>

TestMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section Scripts {
@{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

<div class="text-center">
    <h1 class="display-4">Welcome To Projects Case Management System</h1>
    <p>Click @Html.ActionLink("Here","Index","Cases") To View Cases</p>
    <p>Click @Html.ActionLink("Here","CaseSearch","Cases") to perform a case search
    </p>



</div>

TestMVC/Views/Shared/_CaseSearchResult.cshtml
@using CommonObjectLibraryCore
@model List<Case>

@if (Model.Count() > 0)
{
    <table class="table table-striped table-hover table-sm">
    <thead>
        <tr>
            <th>
                Case Reference
            </th>
            <th>
                Client Name
            </th>
            <th>
                Borrower Names
            </th>
            <th>
                Client Reference
            </th>

        </tr>
    </thead>
    <tbody>
        @foreach (var b in Model)
            {
                <tr>
                    <td>
                        <a asp-controller="CaseDetail" asp-action="Index" asp-route-id="@b.CaseId">@b.CaseReference</a>

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => b.Client.ClientName)
                    </td>
                    <td></td>
                    <td>
                        @Html.DisplayFor(modelItem => b.ClientReference)
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <p>Sorry, no cases found matching your search criteria</p>
}

TestMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projects CMS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TestMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cases"
                                asp-action="CaseSearch">Case Finder</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CaseDetail"
                                asp-action="AddCase">Create New Case</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Projects CMS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


</body>

</html>